// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/mock-recruitment-app": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/mock-recruitment-app";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/mock-recruitment-app";
  };
};