// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
};